// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr2XGw3tE2W46JQzEgCFoAdW5Uv78uOMI',
    appId: '1:235540317989:web:c4ff67f1bf65a7da9d3ccc',
    messagingSenderId: '235540317989',
    projectId: 'appstore-b888c',
    authDomain: 'appstore-b888c.firebaseapp.com',
    storageBucket: 'appstore-b888c.appspot.com',
    measurementId: 'G-C51PEGPBPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxq2i2kXTNywcW96DXuHQ_AU4rFdlRQVc',
    appId: '1:235540317989:android:ef1333e10ef27e4d9d3ccc',
    messagingSenderId: '235540317989',
    projectId: 'appstore-b888c',
    storageBucket: 'appstore-b888c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtNQBBnEh7P5AM34hOI2h-oeU6-zcBk5k',
    appId: '1:235540317989:ios:f999129d5775c3a29d3ccc',
    messagingSenderId: '235540317989',
    projectId: 'appstore-b888c',
    storageBucket: 'appstore-b888c.appspot.com',
    iosBundleId: 'com.example.appstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtNQBBnEh7P5AM34hOI2h-oeU6-zcBk5k',
    appId: '1:235540317989:ios:f999129d5775c3a29d3ccc',
    messagingSenderId: '235540317989',
    projectId: 'appstore-b888c',
    storageBucket: 'appstore-b888c.appspot.com',
    iosBundleId: 'com.example.appstore',
  );
}
